### ISSUE TITLE
installation of rospy and metavision

### ISSUE THREAD

**Issue by nikky4D** [yuyangpoi/FF-KDT#3]
For metavision, would the openeb repo be enough? 

For rospy, I used this link https://github.com/rospypi/simple as 'pip install rospy' failed. Is there a rospy install you prefer?

**Comment by yuyangpoi** [comment]
For rospy instaling, you can ignore it because it's for ImuBuffer and it was not used in this project. 

For Metavision, It seems that OpenEB is enough, we just need the simulator in Core ML modules.
